import type { LineDraft } from "@/modules/order-account-statement/components/oas-types";

/**
 * Order Account Statement formu için örnek satır şablonları ("Örnek doldur" aksiyonları).
 * Saf veri — id'ler kullanım anında üretilir (bkz. emptyLine/newId).
 * (OrderAccountStatementScreen.tsx'ten Faz-1 refactor kapsamında çıkarıldı.)
 */

export const SAMPLE_LINES: Omit<LineDraft, "id">[] = [
  {
    description: "304 Küvet Dondurma (1216 kg * 600 TL/kg)",
    amount: 729_600,
    amountText: "",
    quantityText: "1216",
    unitText: "kg",
    isGift: false,
    unitPriceText: "600",
  },
  {
    description: "5 kg Kese Kağıdı",
    amount: 1_250,
    amountText: "",
    quantityText: "5",
    unitText: "kg",
    isGift: false,
    unitPriceText: "250",
  },
  {
    description: "40 Koli Kornet",
    amount: 40_400,
    amountText: "",
    quantityText: "40",
    unitText: "koli",
    isGift: false,
    unitPriceText: "1010",
  },
  {
    description: "3 Adet El Kaşığı",
    amount: 6_000,
    amountText: "",
    quantityText: "3",
    unitText: "adet",
    isGift: true,
    unitPriceText: "2000",
  },
  {
    description: "4 Adet Sos (40 kg)",
    amount: 8_000,
    amountText: "",
    quantityText: "4",
    unitText: "adet",
    isGift: false,
    unitPriceText: "2000",
  },
  {
    description: "4 Koli Fıstık (40 kg)",
    amount: 4_800,
    amountText: "",
    quantityText: "4",
    unitText: "koli",
    isGift: false,
    unitPriceText: "1200",
  },
  {
    description: "10 Adet Tişört",
    amount: 5_000,
    amountText: "",
    quantityText: "10",
    unitText: "adet",
    isGift: true,
    unitPriceText: "500",
  },
  {
    description: "15 Koli Helva",
    amount: 9_000,
    amountText: "",
    quantityText: "15",
    unitText: "koli",
    isGift: false,
    unitPriceText: "600",
  },
  {
    description: "5 kg Jelatin",
    amount: 900,
    amountText: "",
    quantityText: "5",
    unitText: "kg",
    isGift: false,
    unitPriceText: "180",
  },
  {
    description: "1 Koli Islak Mendil (2000 Adet)",
    amount: 2_700,
    amountText: "",
    quantityText: "1",
    unitText: "koli",
    isGift: false,
    unitPriceText: "2700",
  },
  {
    description: "2 Paket Strafor (72 Adet)",
    amount: 2_500,
    amountText: "",
    quantityText: "2",
    unitText: "paket",
    isGift: false,
    unitPriceText: "1250",
  },
  {
    description: "125 Adet Büyük Çanta",
    amount: 875,
    amountText: "",
    quantityText: "125",
    unitText: "adet",
    isGift: false,
    unitPriceText: "7",
  },
  {
    description: "125 Adet Küçük Çanta",
    amount: 625,
    amountText: "",
    quantityText: "125",
    unitText: "adet",
    isGift: false,
    unitPriceText: "5",
  },
  {
    description: "2 Takım Etiket",
    amount: 4_000,
    amountText: "",
    quantityText: "2",
    unitText: "takım",
    isGift: true,
    unitPriceText: "2000",
  },
];

/** Kısa örnek liste şablonu (kafe / perakende). */
export const SAMPLE_CAFE: Omit<LineDraft, "id">[] = [
  {
    description: "Kahve çekirdek (5 kg)",
    amount: 12_500,
    amountText: "",
    quantityText: "5",
    unitText: "kg",
    isGift: false,
    unitPriceText: "2500",
  },
  {
    description: "Servis malzemesi paketi",
    amount: 3_200,
    amountText: "",
    quantityText: "32",
    unitText: "paket",
    isGift: false,
    unitPriceText: "100",
  },
  {
    description: "Hoş geldin indirimi",
    amount: 500,
    amountText: "",
    quantityText: "1",
    unitText: "adet",
    isGift: true,
    unitPriceText: "500",
  },
];

/** Fırın / üretim satırları örneği. */
export const SAMPLE_BAKERY: Omit<LineDraft, "id">[] = [
  {
    description: "Tip 650 un (25 kg)",
    amount: 18_500,
    amountText: "",
    quantityText: "25",
    unitText: "kg",
    isGift: false,
    unitPriceText: "740",
  },
  {
    description: "Kuru maya (500 g x 20)",
    amount: 4_200,
    amountText: "",
    quantityText: "20",
    unitText: "paket",
    isGift: false,
    unitPriceText: "210",
  },
  {
    description: "Kese kağıdı (baskılı)",
    amount: 6_800,
    amountText: "",
    quantityText: "200",
    unitText: "adet",
    isGift: false,
    unitPriceText: "34",
  },
  {
    description: "Poşet taşıma torbası",
    amount: 2_100,
    amountText: "",
    quantityText: "30",
    unitText: "adet",
    isGift: false,
    unitPriceText: "70",
  },
];

/** Catering / etkinlik satırları örneği. */
export const SAMPLE_CATERING: Omit<LineDraft, "id">[] = [
  {
    description: "Açık büfe kişi başı (120 kişi)",
    amount: 96_000,
    amountText: "",
    quantityText: "120",
    unitText: "kişi",
    isGift: false,
    unitPriceText: "800",
  },
  {
    description: "İkram içecek paketi",
    amount: 14_500,
    amountText: "",
    quantityText: "145",
    unitText: "paket",
    isGift: false,
    unitPriceText: "100",
  },
  {
    description: "Servis personeli (8 saat)",
    amount: 22_000,
    amountText: "",
    quantityText: "8",
    unitText: "saat",
    isGift: false,
    unitPriceText: "2750",
  },
  {
    description: "Tek kullanımlık servis seti",
    amount: 8_750,
    amountText: "",
    quantityText: "250",
    unitText: "adet",
    isGift: false,
    unitPriceText: "35",
  },
];
